---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda DB API"

Resources:
  KendraIndexingRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: KendraIndexing
      KendraIndexingPolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "kendra.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Resource: "*"
            Action:
              - "logs:DescribeLogGroups"
          - Effect: "Allow"
            Resource:
              Fn::Join: [":", ["arn:aws:logs", !Ref "AWS::Region", !Ref "AWS::AccountId", "log-group:/aws/kendra/*"]]
            Action:
              - "logs:CreateLogGroup"
          - Effect: "Allow"
            Resource:
              Fn::Join: [":", ["arn:aws:logs", !Ref "AWS::Region", !Ref "AWS::AccountId", "log-group:/aws/kendra/*:log-stream:*"]]
            Action:
              - "logs:DescribeLogStreams"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"

#        {
#            "Effect": "Allow",
#            "Action": "cloudwatch:PutMetricData",
#            "Resource": "*",
#            "Condition": {
#                "StringEquals": {
#                    "cloudwatch:namespace": "Kendra"
#                }
#            }
#        },

# S3 access